---
title: Push Station
---

flowchart
    start((Begin))
    start-->getStation["subRootStation = GetStationById(stationId)"]
    getStation-->checkStation{"if subRootStation == null"}
    checkStation--yes-->exit((Exit))
    checkStation--no-->connectStation["subRootStation.PushStation(stationToConnect)"]
    connectStation-->exit