---
title: CalculateTimer of Verse
---

flowchart
    Start((Begin))
    Start --> max["max = tracks[0].length"]
    max --> i["for i = 0 to tracks.length - 1"]
    i --> check{"tracks[i].length > max"}
    check -->|T| setMax["max = tracks[i].length"]
    check -->|F| i
    i --> End((return max))