class Engine:
    def __init__(self) -> None: ...
    def get_station_network(self) -> 'StationNetwork': ...
    def get_media_binder(self) -> 'MediaBinder': ...
    def get_current_time(self) -> float: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def rewind(self) -> None: ...


class StationNetworkSerializer:
    def __init__(self, engine: Engine) -> None: ...
    def import_spi_file(self, file_path: str) -> None: ...


class Clip:
    media_type: str
    media_path: str
    def __bool__(self) -> bool: ...

class VideoClip(Clip):
    start: float
    end: float
    def __init__(self, media_path: str, start: float, end: float) -> None: ...

class Track:
    def __init__(self) -> None: ...
    def get_clip(self, position: int) -> Clip: ...
    def get_clip_count(self) -> int: ...

class Verse:
    def __init__(self) -> None: ...
    tracks: list[Track]
    

class StationNetwork:
    def __init__(self) -> None: ...
    def size(self) -> int: ...

class MediaBinder:
    def __init__(self) -> None: ...
    def bind_verse(self, verse: str) -> None: ...
    def unbind_verse(self) -> None: ...
    def get_verse(self) -> 'Verse': ...
    def data_to_bind(self, time: float) -> 'Clip': ...