block-beta

    columns 4

    32bits:4
    nos["Number of stations"]:2
    nov["Number of videos"]:2
    lofs["Location of first station"]:4
    restOfStations["..."]:4
    loes["Location of end station"]:4
    lofv["Location of first video"]:4
    restOfVideos["..."]:4
    loev["Location of end video"]:4
    space:4
    timelapse["Timelapse"]:4
    lifetime["Station lifetime"]:4
    station_type["Station type"]:1
    n_threads["Number of threads"]:1
    1_v_thread["First video thread"]:1
    rest_of_threads["..."]:1
    n_v_thread["Last video thread"]:1

    metadata["Metadata"]:3

    space:4

    videoBuffer["Video buffer"]:4
