sequenceDiagram
    actor Client
    participant Application
    participant MediaBinder
    participant StationManager

    Client->>Application: Travel(thread)
    Application->>MediaBinder: BindVerse(nextStation.verse(thread))
    Application->>StationManager: Travel(thread)
    Application->>TimeService: ResetPlayingTime()
