sequenceDiagram
    actor Client
    participant Application
    participant TimeService
    participant MediaBinder
    participant StationManager

    Client->>Application: OnUpdate(delta)
    Application->>TimeService: StepTime(delta)
        Application->>MediaBinder: DataToBind()
        MediaBinder--)Application: return data
    break when dataToBind != null
        Application-->>Client: return data
    end
    Application->>StationManager: CheckTimelapse()
    break when currentTime > nextStationTime && not stationed
        StationManager-->>Application: GetNextStation()
        Application-->>Client: return station
    end
