classDiagram
    class HistoryStation {
        - stationsToUse: List~Number~
        - gates: Map~String, Number~

        + useStation(stationId: Number) void
        + removeStation(stationId: Number) void
        + GetStationIds() List~Number~

        + CreateGate() void
        + SetGate(gateName: String, gateValue: Number) void
        + GetGate(gateName: String) Number
        + GetGates() Map~String, Number~
        + AutoRoad() Number
    }

    HistoryStation --> Station